### ISSUE TITLE
Theme update broke display of form in FE

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/clarity-theme#11]
After the last [update](https://github.com/clarity-h2020/clarity-theme/commit/e9bde83dce54a2a2c82eacf7da7c240e90835157) of the theme the forms shown in the Study are broken:
![error-context form](https://user-images.githubusercontent.com/42167036/65426122-e5a23780-de0f-11e9-994c-c6e3caca9eae.png)

This is caused by an override statement in the info.yml file of the theme right [here](https://github.com/clarity-h2020/clarity-theme/commit/e9bde83dce54a2a2c82eacf7da7c240e90835157#diff-ac1946206b086860bebd6433e069d409R17). For now, I just removed this line of code, since we need to be able to work with the forms right away. But at some point this should get fixed in a different way, since I'm sure @bullz added this override statement for a reason.

Additionally, also the second override statement (assets/vendor/jquery.ui/themes/base/theme.css) should be fixed, since it also breaks the form display in the front-end a little bit. However, I left that statement since its effects are not as dramatic.

**Comment by patrickkaleta** [comment]
@bullz just so you know, the problem is caused by a missing `:before` css-rule for `.ui-helper-cleafix`, which is available in the core.css that was overwritten in the latest theme update.
![missing-css_rules](https://user-images.githubusercontent.com/42167036/65426626-e091b800-de10-11e9-92d1-2f51bcd3e1f1.png)

**Comment by DenoBeno** [comment]
Fixed now? Excellent.

**Comment by patrickkaleta** [comment]
No, it's not yet fixed. I only implemented a workaround by removing a [statement](https://github.com/clarity-h2020/clarity-theme/commit/e9bde83dce54a2a2c82eacf7da7c240e90835157#diff-ac1946206b086860bebd6433e069d409R17), which was added by @bullz in one of his previous theme updates. I'm assuming he added this line for a reason, so he should eventually look into this and fix it properly.

**Comment by patrickkaleta** [comment]
@bullz please fix this. We just noticed together with @DenoBeno that the Cancel button (**X** in upper right corner) is not visible, but still functional. So, closing those pop-ups can be quite tricky if the users don't know that there actually is a cancel button hidden in the top corner.

**Comment by p-a-s-c-a-l** [comment]
Please close this issue if this has been resolved in the [updated theme](https://github.com/clarity-h2020/clarity-theme/issues/17) or give feedback on the status.

**Comment by patrickkaleta** [comment]
No, cancel-buttons are still missing on all the forms. They are there (you can click on them and they work), but they are just not visible to anyone. It is not a permissions issue, this needs to be fixed in the theme. @bullz please take care of that. 
![missing cancel button](https://user-images.githubusercontent.com/42167036/75038000-b888ac80-54b5-11ea-8d1f-139cd66d9aa2.png)

**Comment by patrickkaleta** [comment]
This is now finally fixed!
